---
- name: Install python3
  apt:
    name: python3
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install Flask using pip
  pip:
    name: flask
    state: present
    executable: pip3

