---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

# tasks file for dbserver
